name: CI Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t devops-job-tracker:latest .

    - name: Debug DockerHub Credentials
      run: |
        echo "DockerHub Username: ${{ secrets.DOCKER_USERNAME }}"
        # Do not print DockerHub Password in the logs for security reasons

    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to DockerHub
      run: |
        docker tag devops-job-tracker:latest ${{ secrets.DOCKER_USERNAME }}/devops-job-tracker:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-job-tracker:latest

