name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t devops-job-tracker:latest .

    - name: Validate DockerHub secrets
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME is missing"
          exit 1
        else
          echo "✅ DOCKER_USERNAME is set"
        fi

        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD is missing"
          exit 1
        else
          echo "✅ DOCKER_PASSWORD is set"
        fi

    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag and Push Docker image to DockerHub
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/devops-job-tracker:latest
        docker tag devops-job-tracker:latest $IMAGE_NAME
        docker push $IMAGE_NAME
